#include "compactador.c"

#ifndef FILESYSTEM_Y_LISSANDRA_COMPACTADOR_INICIARCOMPACTADOR_H_
#define FILESYSTEM_Y_LISSANDRA_COMPACTADOR_INICIARCOMPACTADOR_H_


#endif /* FILESYSTEM_Y_LISSANDRA_COMPACTADOR_INICIARCOMPACTADOR_H_ */
